# Site settings
title: xuguanqun
description: 'xuguanqun personal blog'
baseurl: '/'
url: 'https://xuguanqun.github.io'

# Google Analytics
google_analytics: G-T44GZGJWXV

# Author
author:
  name: xuguanqun
  url: https://github.com/xuguanqun
  email: imlostdeer@gmail.com

# Build settings
markdown: kramdown
include:
  - _pages

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink: /:year-:month-:day/:title
paginate: 5

# Excludes
exclude: [Gemfile, Gemfile.lock, tale.gemspec]

# Disqus (Set to your disqus id)
disqus: jekyll-tale
